### PR TITLE
check real long enum value in integration test

### PR DESCRIPTION
**Pull request by tchaloupka**

### CODE REVIEW

**Comment by denizzzka** [comment]
Because "Int8" is used... Hmmm.... Can we use this as enum? In is passes PG conversion into PG's enum?,,

**Comment by denizzzka** [comment]
Actually this is not a check for enum size because test isn't accept PG enum type

**Comment by tchaloupka** [comment]
As we discussed here: https://github.com/denizzzka/dpq2/pull/94#discussion_r175387088
Currently enums are converted to their base integral value to store in the DB so ie:
```D
enum foo {bar}
auto v = foo.bar.toValue;
assert(v.as!int == 0);
```

Only string based enums are sent as a text values and when return, they have to be converted to text.
As I mentioned PG supports enums, but problem is with their Oids that vary so we can't simply do something like:

```D
enum foo {bar, baz}
conn.exec("CREATE TYPE foo AS ENUM ('bar', 'baz')");
auto res = conn.execparams(QueryParams("SELECT 'baz'::foo"));
foo f = res[0][0].as!foo;
```
as we don't know anything about foo's OID.

only this works:
```
enum foo : string {bar="bar", baz="baz"}
conn.exec("CREATE TYPE foo AS ENUM ('bar', 'baz')");
auto qp = QueryParams("SELECT 'baz'::text");
auto res = conn.execparams(qp);
foo f = res[0][0].as!foo;
```
and writing enum to the foo typed column too in this case.

Enum types are sent as text data in binary protocol.
One possibility was to send enums by their names and read them alike but ignoring the oid check and that neither of us liked so we ended up with a compromise:
* integral typed enums -> integral DB types
* string typed enums -> text DB type which can be used in custom set enum type implicitly but needs to be converted to text when read.

**Comment by denizzzka** [comment]
Also, probably, this is answer to https://github.com/denizzzka/dpq2/issues/98

**Comment by denizzzka** [comment]
> Currently enums are converted to their base integral value to store in the DB so ie:

So, why D's long enum support is important? As I understand, big long value will throw SQL error at try to cast it to enum.

**Comment by tchaloupka** [comment]
> So, why D's long enum support is important? As I understand, big long value will throw SQL error at try to cast it to enum.

I don't understand the question. Where is the long value to PG SQL enum casting?
This is the conversion done in the current implementation:

D's type|PG type
-|-
`enum : short`|`Int2`
`enum : int`|`Int4`
`enum: long`|`Int8`
`enum : string`|`text`

The only PG enum conversion is when you do something like this:
```SQL
CREATE TYPE foo AS ENUM ('foo', 'bar', 'baz');
CREATE TABLE foos (
	"id" SERIAL8 PRIMARY KEY,
	"foo" foo NOT NULL
);
```
```D
enum foo : string {foo="foo",bar="bar", baz="baz"}
auto qp = QueryParams("INSERT INTO foos (foo) VALUES ($1)");
qp.args = [foo.bar.toValue];
conn.execParams(qp);
```

**Comment by denizzzka** [comment]
> I don't understand the question. Where is the long value to PG SQL enum casting?

Native types is supported (it is already implemented years ago).

But you want to support D's `enum : long` too. Why?  It is impossible to use long enum in PG database. We already can pass `int8` to PG (and can convert it from D's enum) but why it is need to ability to convert D's integer enums other than `int` to PG integer values?

**Comment by tchaloupka** [comment]
But long enum is not converted to PG's enum, but just to basic Int8 PG type.
So why support `enum:int` in the first place (which is also converted only to the basic number of `Int4` type) when you don't want to support types like short, ushort, byte, long, etc?

To add to previous example:
```SQL
INSERT INTO foos (foo) VALUES (1::Int4); -- doesn't work
INSERT INTO foos (foo) VALUES (1::foo); -- doesn't work
INSERT INTO foos (foo) VALUES ('bar::foo); -- works
INSERT INTO foos (foo) VALUES ('bar'); -- works
```
There is no simple way to convert D's integral types to PG's enum. For that only way is to use text values.
That's why I don't understand the point for the D's long enums as they can be only stored in `Int8` columns if we don't use named values pass for all the enums. But then there is a mentioned problem with Oids to read them back.
But after all it can be a more correct way to handle all D's enums - all passed by their text value.

For the record, I don't think that long enums are used for storing so many value variants, who will write them all? :) But I've seen them being used as a few value variants with some long numbered constants or bit flags (they can't be stored as PG's enum anyway and will be stored just as Int8 - as is the current behavior)

**Comment by denizzzka** [comment]
> But long enum is not converted to PG's enum, but just to basic Int8 PG type.

Yes

> So why support enum:int in the first place

Because PG enum is also `Int4`

> (which is also converted only to the basic number of Int4 type)

Unfortunately, I did not notice immediately that there is no support for enum Oid in PG. I would not agreed to such a patch at all. Sorry.

> when you don't want to support types like short, ushort, byte, long, etc?

This is one way conversations can be done manually.

**Comment by tchaloupka** [comment]
So basically there are 3 ways to handle the enums I think:

1. Don't handle them at all and leave it to the user of the library co convert them to desired types
2. Handle integral enums as integer PG types and string enums as text types (which can be implicitly converted to PG's enum values) - current behavior
3. Handle all enums as text values so they will work with PG enums except that when they are readed back, they would have an unknown Oid (which we can trust implicitly and don't check it - we both don't like it much) or must be explicitly converted to text values for succesfull read back

**Comment by denizzzka** [comment]
3 isn't have many sence because it will be too slow

**Comment by denizzzka** [comment]
> As they are not being transfered as Int4 but as text value despite that in PG documentation in implementation details for enum types it is said that they are being stored as Int4.

Carramba! My bad. Read it right now.

**Comment by tchaloupka** [comment]
Only info I've found Is in PG sourves itself: https://github.com/postgres/postgres/blob/9d4649ca49416111aee2c84b7e4441a0b7aa2fac/src/backend/utils/adt/enum.c

See functions enum_recv and enum_send.
You can also just try and look at the data returned from the DB

**Comment by denizzzka** [comment]
Huh. Thanks!

1. Looks like (3) with "must be implicitly converted to text values for successful read back" will be best choice.

But, if we can't check or set Oid in case of "implicitly converted to text" I would vote for the removal of enums support because it leads to bugs.

**Comment by denizzzka** [comment]
(Once again I'll write that I already regret about adding support for the enums. Probably, this was a mistake.)

**Comment by tchaloupka** [comment]
ok, made a PR to remove it and leave it to the user

**Pull request closed without merging**
