### PR TITLE
Implement GitHub Actions

### LINKED ISSUE #153: Travis-CI -> another CI system

### PR DESCRIPTION
**Pull request by hatf0**
Fixes #153.

With this, all commits are tested across 8 different compiler versions (dmd-master, dmd-beta, dmd-latest, dmd-2.098.1, ldc-master, ldc-latest, ldc-beta, ldc-1.28.1) and both linking types (static, dynamic). Additionally, this will automatically deploy to GitHub Pages on new commits to master with no intervention needed (although, you may need to change the root that GitHub Pages serves from). I also updated the README.md to reflect this change.

Let me know if this needs anything else! Thanks.

### CODE REVIEW

**Comment by maxhaton** [comment]
There's some missing new lines at the end of some files, if you care.

**Comment by maxhaton** [comment]
If the CI for this project is reliable you could also add it to the dlang buildkite

**Comment by denizzzka** [comment]
@hatf0 Thank you!

**Comment by denizzzka** [comment]
@maxhaton just yet another CI facility?

**Comment by maxhaton** [comment]
> @maxhaton just yet another CI facility?

It's part of the CI for the D compiler and library. The change we make to the compiler gets tested against all the projects in buildkite, so we can test on more complicated code than what we have in the test suite.

It depends on the project being tested though. Simple code is great to have in buildkite but anything that does networking can be a total nightmare due to flakiness.

**Pull request merged**
