### PR TITLE
WIP: Support Date in rawValueToBson

### PR DESCRIPTION
**Pull request by nordlow**

### CODE REVIEW

**Comment by nordlow** [comment]
Closing in favor of https://git.symmetry.dev/symmetry/code/SIL/plugins/alpha/postgres/-/merge_requests/36, @denizzzka.

**Comment by nordlow** [comment]
Ping, @denizzzka.

**Comment by denizzzka** [comment]
Please wait a hour, it is need to add tests

**Comment by denizzzka** [comment]
Bson type `Date` actually is: _a 64-bit integer that represents the number of milliseconds since the Unix epoch (Jan 1, 1970)_

Bson isn't supports SQL or Dlang analog for Date type. I think it's wrong to try to turn timestamps it sort of Date type

**Pull request closed without merging**
