### PR TITLE
columnExists for Row struct

### PR DESCRIPTION
**Pull request by burner**
I guess the title says it all.
Just propagates the call to answer.

### CODE REVIEW

**Comment by burner** [comment]
thank you

**Comment by burner** [comment]
is there a chance to get a release for this function?

**Comment by denizzzka** [comment]
ohh, sure

**Comment by burner** [comment]
can we also get a new vibe.d.db.postgresql release?

**Comment by denizzzka** [comment]
> can we also get a new vibe.d.db.postgresql release?

Probably, no significand changes in it since last release

**Pull request merged**
