### PR TITLE
Fix #122 -- toValue should support Nullable!DateTime

### LINKED ISSUE #122: Nullable!DateTime isn't supported for toValue
```D
DateTime dt;
auto v = dt.toValue; // OK
Nullable!DateTime ndt = dt;
auto v = ndt.toValue; // Error, unsupported type: DateTime
```
I've traced it down to the fact that the specialized version of `toValue` for `Nullable` is checking if the value is null, and then *bypassing* the "hack" to convert `DateTime` into `Timestamp` if it is null (since it needs the oid I'm assuming).

A possible fix here is to implement the same hack for `Nullable!DateTime`. I'll work on a PR.

### PR DESCRIPTION
**Pull request by schveiguy**

### CODE REVIEW

**Comment by denizzzka** [comment]
Strange! It was planned that `DateTime` or any another type should not require a special case here.

**Comment by denizzzka** [comment]
Maybe `detectOidTypeFromNative` is not working properly for `DateTime`?

**Comment by denizzzka** [comment]
Found what `DateTime` support was replaced by dpq2's own struct:
https://github.com/denizzzka/dpq2/issues/90

**Comment by denizzzka** [comment]
Fixed in #124 

Thanks!

**Comment by schveiguy** [comment]
> Strange! It was planned that `DateTime` (or any another type) should not require a special case here.

The reason `toValue(DateTime)` works is because there is a specific case for it. I don't know the history of the library, but most definitely it appears to be a "hackish" workaround: https://github.com/denizzzka/dpq2/blob/18515d20b9bf68e5665aa74c62e33b7e0278810b/src/dpq2/conv/from_d_types.d#L165

This led me to believe that it was an "afterthought", and maybe that was added afterwards to appease some use case without thinking about the `Nullable!DateTime` case.

I thought of solving it in the oid function, but I also didn't know if that might break anything else. I did the least intrusive thing in my PR :)

But thanks for fixing it!

**Pull request closed without merging**
