### PR TITLE
Value copying is disabled for users

### PR DESCRIPTION
**Pull request by denizzzka**
Please check this

### CODE REVIEW

**Comment by denizzzka** [comment]
I just do not know if it will work and isn't broke anything?

**Comment by tchaloupka** [comment]
I tried this against my codebase and only problem with this is with some caching of Values to use in query.
So I would be fine with this change if it only affects db -> code as values should be used just to read requested types from them.
But other way around it is causing problems as ie `qp.args[0] = fooVal` isn't possible then

**Comment by denizzzka** [comment]
> But other way around it is causing problems as ie qp.args[0] = fooVal isn't possible then

Try to use 
```d
    /// Fills out arguments from variadic arguments
    void argsVariadic(Targs ...)(Targs t_args)
```

**Comment by denizzzka** [comment]
> Returns data directly and so escaping the pointer to not so immutable data.

`if(is(T : const ubyte[]))` is const or immutable pointer to const or immutable data - this should be ok for immutable Value data (as I understand D)

**Comment by tchaloupka** [comment]
But that is only template condition. What I think is a problem is `return v.data;`.
There is no data copying (or I don't see it) so pointer to `Value._data` is returned and as `_data` is slice from PGresult it becames invalid when it is cleared.

This is the Value construction from the result:
```D
// The pointer returned by PQgetvalue points to storage that is part of the PGresult structure.
// One should not modify the data it points to, and one must explicitly copy the data into other
// storage if it is to be used past the lifetime of the PGresult structure itself.
immutable ubyte* v = cast(immutable) PQgetvalue(answer.result, to!int(row), to!int(col));
size_t s = size(col);

return immutable Value(v[0..s], answer.OID(col), isNULL(col), answer.columnFormat(col));
```

**Comment by denizzzka** [comment]
> There is no data copying (or I don't see it) so pointer to Value._data is returned and as _data is slice from PGresult it becames invalid when it is cleared.

Yes.
```D
package this(this) pure {}
```

Prohibits (?) escaping from `Answer` scope, also I am planning to use DIP1000 for Value in the furute

**Comment by tchaloupka** [comment]
```D
QueryParams qp = QueryParams("SELECT 1");
auto res = conn.execParams(qp);
writeln(&res[0][0]._data[0]);
immutable(ubyte)[] copy = res[0][0].data;
writeln(&copy[0]);
```

I get:
```D
172E938
172E938
```
So the disabled copy constructor is bypassed by data property itself.

This is prohibited and won't compile:
```D
QueryParams qp = QueryParams("SELECT 1");
auto res = conn.execParams(qp);
auto val = res[0][0];
writeln(val.as!int);
```

**Comment by denizzzka** [comment]
> So the disabled copy constructor is bypassed by data property itself.

1. `_data` is `package`
2. it is legal to copy immutable values by this way. In this case compiler cares only about reference counting.

> This is prohibited and won't compile:

It is unpleasant. Probably then I am not merge this PR and we will live as before. Until dip1000 will be implemented.

**Comment by denizzzka** [comment]
Or it is need another mechanism to prohibit copying of `Value` that referenced to `Answer`

**Pull request closed without merging**
